### ISSUE TITLE
Impossible d'ouvrir l'application sous Max OS Catalina

### ISSUE THREAD

**Issue by theo88400** [GabrielVidal1/AutochessViewerACDC#22]
<img width="756" alt="Capture d’écran 2020-05-06 à 15 05 12" src="https://user-images.githubusercontent.com/58563817/81180305-1c961980-8fab-11ea-9237-2864696ed5b4.png">

Bonjour, je n'arrive pas à ouvrir l'application sur Mac OS Catalina (10.15.4).
J'ai voulu télécharger les sources pour essayer de compiler moi-même mais dans l'archive contenant le source code, il y a seulement un README.md
Si besoin, je me tiens disponible pour aider pour les tests sur mac.
Merci.

**Comment by epitavy** [comment]
Effectivement, tu ne peux pas ouvrir l'application comme une app normale, le build sous Unity pour OSX doit être configuré différemment, c'est pour ça que ça ne marche pas.

La procédure est la suivante:
- Aller dans le dossier de l'app puis dans `AutochessViewer_Mac/AutochessViewer_Mac.app/Contents/MacOS`
- Entrer la commande `chmod +x AutochessViewer`
- Entrer la commande `./AutochessViewer` (l'app s'ouvre mais il y a des problèmes de permissions apparemment, vous pouvez cliquer sur Ok)
- Aller dans Préférence Système -> Sécurité et Confidentialité et cliquer sur le bouton "Ouvrir quand même"
- L'application peut maintenant être ouverte normalement, soit un l'ouvrant depuis le Finder,
soit en exécutant la commande `open AutochessViewer/AutochessViewer.app`

**Comment by theo88400** [comment]
Ca fonctionne parfaitement. Merci !
