### ISSUE TITLE
Pas de bouton AddEntity et Exit

### ISSUE THREAD

**Issue by SteveNoobGeek** [GabrielVidal1/AutochessViewerACDC#23]
Je suis sur la dernière version du Viewer sous Windows, et comparé au tuto, je ne vois pas ces deux boutons. Le problème c'est que je ne peux créer de config sans ajouter d'unités. J'ai essayé de le faire sous la VM avec Linux mais je n'ai pas compris comme exécuter le fichier. De l'aide ?
![Viewer](https://user-images.githubusercontent.com/31375501/81320545-a7514400-9091-11ea-8686-758bb99662c9.PNG)

**Comment by JulienMayer** [comment]
Même problème sous MacOS, je n'ai pas trouvé de solution ...

**Comment by SteveNoobGeek** [comment]
Et du coup comment l'installer et l'exécuter sur Linux du coup @JulienMayer ?

**Comment by JulienMayer** [comment]
je n'ai pas eu de problème lors de l'installation personnellement, juste cliquer sur le lien du ficher pour Mac et je l'ai ouvert depuis finder une fois le chargement terminer. Aussi ca doit être mon ordi mais il est super lourd a faire tourner sur ma machine, mon ventilo s'affole a chaque fois que je l'ouvre.

**Comment by GabrielVidal1** [comment]
C'est un problème de résolution d'écran, je règle ça au plus vite

**Comment by SteveAndMore** [comment]
D'accord

**Comment by GabrielVidal1** [comment]
C'est bon ça a été fix, tu peux télécharger la nouvelle version du viewer [ici](https://github.com/GabrielVidal1/AutochessViewerACDC/releases)
